[project]
name = "learn-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "fastapi>=0.116.1",
    "isort>=6.0.1",
    "pydantic>=2.11.7",
    "ruff>=0.12.12",
    "scalar-fastapi>=1.3.0",
    "uvicorn>=0.35.0",
]
